### ISSUE TITLE
Fit logarithmic data

### ISSUE THREAD

**Issue by Rykath** [redmod-team/profit#99]
## Description
Currently `fit` fails with logarithmic input data and logarithmic outputs.

## Example

![log_fit_210423](https://user-images.githubusercontent.com/18230626/115853729-c32c3200-a429-11eb-8d24-09f77843a5eb.png)

![log_fit2_210423](https://user-images.githubusercontent.com/18230626/115853913-fa9ade80-a429-11eb-8f90-f42078792bf1.png)

## Workaround
Modify input and output data manually / with postprocessor

**Comment by Rykath** [comment]
The presented bug is actually partially due to #106. With a rescaling of the data, the fit works better but still does not fully capture the shape of the curve.

![image](https://user-images.githubusercontent.com/18230626/116531459-79d35b00-a8df-11eb-9b55-00659a11f55b.png)

**Comment by krystophny** [comment]
There is a more general issue when sampling according to some (e.g. Normal) distribution and constructing a surrogate. Samples in parameter space will not be equidistant anymore. A way to circumvent this would be to generally use a transformation via the cumulative distribution function (CDF) on uniform samples (usually quasirandom with Halton). See https://en.wikipedia.org/wiki/Inverse_transform_sampling . Code example (plot with `hist` to verify):
```python
import numpy as np
from scipy.special import erfinv
r = np.random.rand(1000)
rn = np.sqrt(2.0)*erfinv(2.0*r - 1.0)
```

For 2D with Halton instead of random numbers:
```python
from profit.util.halton import halton
r = halton(1000, 2)
rn = np.empty_like(r)
mu = np.array([0.1, -0.5])
sig = np.array([0.01, 0.2])
rn[:,0] = mu[0] + sig[0]*np.sqrt(2.0)*erfinv(2.0*r[:,0] - 1.0)
rn[:,1] = mu[1] + sig[1]*np.sqrt(2.0)*erfinv(2.0*r[:,1] - 1.0)
```

In the end one also needs to shift mean and scale variance accordingly
